/** @format */

export const locations = [
  "Abchurch Lane",
  "Abchurch Yard",
  "Adams Court",
  "Aldermanbury",
  "Aldermanbury Square",
  "Aldermans Walk",
  "Aldgate",
  "Aldgate High Street",
  "Allhallows Lane",
  "Amen Corner",
  "Amen Court",
  "America Square",
  "Angel Court",
  "Angel Lane",
  "Apothocary Street",
  "Arthur Street",
  "Austin Friars",
  "Ave Maria Lane",
  "Barbican",
  "Barbican, Brandon Mews",
  "Barbican, Lambert Jones Mews",
  "Barbican, Lauderdale Place",
  "Barbican, Shaftesbury Place",
  "Barbican, Speed Highwalk",
  "Barbican, St. Giles Churchyard",
  "Barbican, St. Giles Terrace",
  "Barbican, The Postern",
  "Barbican, Wallside",
  "Bartholomew Lane",
  "Basinghall Avenue",
  "Basinghall Street",
  "Bassishaw Highwalk",
  "Bastion Highwalk",
  "Bell Inn Yard",
  "Bell Wharf Lane",
  "Bengal Court",
  "Bennet's Hill",
  "Bevis Marks",
  "Billiter Street",
  "Birchin Lane",
  "Bishopsgate",
  "Bishopsgate Arcade",
  "Bishopsgate Churchyard",
  "Black Friars Lane",
  "Blake Morgan, New Street Square",
  "Blomfield Street",
  "Bolt Court",
  "Booth Lane",
  "Botolph Alley",
  "Botolph Lane",
  "Bouverie Street",
  "Bow Churchyard",
  "Bow Lane",
  "Brabant Court",
  "Bread Street",
  "Bream's Buildings",
  "Bride Court",
  "Bride Lane",
  "Bridewell Place",
  "Bridgewater Square",
  "Broad Street Place",
  "Broadgate",
  "Broken Wharf",
  "Bulls Head Passage",
  "Burgon Street",
  "Bury Street",
  "Bush Lane",
  "Byward Street",
  "Camomile Street",
  "Cannon Street",
  "Carey Lane",
  "Carlisle Avenue",
  "Carmelite Street",
  "Carter Court",
  "Carter Lane",
  "Castle Baynard Street",
  "Castle Court",
  "Cheapside",
  "Cheapside Passage",
  "Church Entry",
  "Clement's Lane",
  "Clifford's Inn Passage",
  "Cloak Lane",
  "Coleman Street",
  "College Hill",
  "College Street",
  "Compter Passage",
  "Cooper's Row",
  "Copthall Avenue",
  "Cornhill",
  "Cousin Lane",
  "Crane Court Lane",
  "Creed Lane",
  "Crescent",
  "Crosswall",
  "Crown Court",
  "Crutched Friars",
  "Cullum Street",
  "Cursitor Street",
  "Deans Court",
  "Devonshire Row",
  "Devonshire Square",
  "Distaff Lane",
  "Dorset Rise",
  "Dowgate Hill",
  "Dukes Place",
  "East Harding Street",
  "Eastcheap",
  "Eldon Street",
  "Exchange Arcade",
  "Falcon Court",
  "Fann Street",
  "Farringdon Street",
  "Fenchurch Avenue",
  "Fenchurch Place",
  "Fenchurch Street",
  "Fetter Lane",
  "Finch Lane",
  "Finsbury Avenue",
  "Finsbury Circus",
  "Finsbury Street",
  "Fish Street Hill",
  "Fleet Place",
  "Fleet Street",
  "Fore Street",
  "Fore Street Avenue",
  "Foster Lane",
  "Frederick's Place",
  "Friar Street",
  "Friday Street",
  "Frobisher Crescent",
  "Furnival Street",
  "Garlick Hill",
  "George Yard",
  "Godliman Street",
  "Goring Street",
  "Gough Square",
  "Great New Street",
  "Great St. Helen's",
  "Great St. Thomas Apostle",
  "Great Swan Alley",
  "Great Tower Street",
  "Great Winchester Street",
  "Gresham Street",
  "Greystoke Place",
  "Groveland Court",
  "Guildhall Buildings",
  "Guildhall Yard",
  "Gutter Lane",
  "Harp Lane",
  "Hart Street",
  "Haydon Street",
  "Heneage Lane",
  "High Timber Street",
  "Hind Court",
  "Honey Lane",
  "Houndsditch",
  "Idol Lane",
  "India Street",
  "Inner Temple Lane",
  "Ireland Yard",
  "Ironmonger Lane",
  "Jewry Street",
  "John Carpenter Street",
  "Johnsons Court",
  "King Street",
  "King William Street",
  "Kings Arms Yard",
  "Knightrider Court",
  "Knightrider Street",
  "Lambeth Hill",
  "Laurence Pountney Hill",
  "Laurence Pountney Lane",
  "Lawrence Lane",
  "Leadenhall Market",
  "Leadenhall Place",
  "Leadenhall Street",
  "Lime Street",
  "Limeburner Lane",
  "Little New Street",
  "Little Trinity Lane",
  "Liverpool Street",
  "Lloyd's Avenue",
  "Lombard Court",
  "Lombard Lane",
  "Lombard Street",
  "London Street",
  "London Wall",
  "London Wall Buildings",
  "Lothbury",
  "Lovat Lane",
  "Love Lane",
  "Lower New Change Passage",
  "Lower Thames Street",
  "Ludgate Broadway",
  "Ludgate Circus",
  "Ludgate Hill",
  "Ludgate Square",
  "Mansion House Place",
  "Mark Lane",
  "Martin Lane",
  "Mason's Avenue",
  "Milton Street",
  "Mincing Lane",
  "Minories",
  "Minster Court",
  "Minster Pavement",
  "Mitre Street",
  "Monkwell Square",
  "Monument Street",
  "Moor Lane",
  "Moorfields",
  "Moorfields Highwalk",
  "Moorgate",
  "Moorgate Place",
  "Nevill Lane",
  "New Bridge Street",
  "New Broad Street",
  "New Change",
  "New Change Passage",
  "New Fetter Lane",
  "New London Street",
  "New Street",
  "New Street Square",
  "Nicholas Lane",
  "Noble Street",
  "Northumberland Alley",
  "Oat Lane",
  "Octagon Arcade",
  "Old Bailey",
  "Old Billingsgate Walk",
  "Old Broad Street",
  "Old Change Court",
  "Old Jewry",
  "Old Mitre Court",
  "Paternoster Row",
  "Paternoster Square",
  "Paul's Walk",
  "Pemberton Row",
  "Pepys Street",
  "Philpot Lane",
  "Pilgrim Street",
  "Priory Court",
  "Playhouse Yard",
  "Pleydell Street",
  "Plough Place",
  "Plumtree Court",
  "Poppins Court",
  "Poultry",
  "Princes Street",
  "Printer Street",
  "Printers Inn Court",
  "Pudding Lane",
  "Puddle Dock",
  "Queen Street",
  "Queen Street Place",
  "Queen Victoria Street",
  "Queenhithe",
  "Queens Head Passage",
  "Red Lion Court",
  "Rolls Passage",
  "Rood Lane",
  "Ropemaker Street",
  "Rose Street",
  "Royal Court",
  "Royal Exchange",
  "Royal Exchange Avenue",
  "Royal Exchange Buildings",
  "Royal Mint Court",
  "Russia Row",
  "Salisbury Court",
  "Salisbury Square",
  "Salters Hall Court",
  "Savage Gardens",
  "Seething Lane",
  "Serjeant's Inn",
  "Ship Tavern Passage",
  "Shoe Lane",
  "Sky Garden Walk",
  "South Place",
  "St. Andrew Street",
  "St. Andrew's Hill",
  "St. Botolph Street",
  "St. Bride Street",
  "St. Bride's Avenue",
  "St. Brides Passage",
  "St. Clare Street",
  "St. Dunstan's Hill",
  "St. Georges Lane",
  "St. Helen's Place",
  "St. James's Passage",
  "St. Mary At Hill",
];
