/** @format */

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavHeader from "./_components/NavHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <title>Prestige</title>
      </head>
      <body>
        <div className=" fixed top-0 w-full z-10">
          <NavHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
